set(VTKDEMOS_PACKAGE_VERSION 1.0.0)
set(VTKDEMOS_DEPENDS REQUIRED Equalizer Boost VTK)

set(VTKDEMOS_ROOT_VAR VTKDEMOS_ROOT)
#set(VTKDEMOS_REPO_URL https://github.com/hernando/VTKDemos.git)
set(VTKDEMOS_REPO_URL ssh://git@bb4.cesvima.upm.es/VTKDemos.git)
set(VTKDEMOS_REPO_TAG master)

set(VTKDEMOS_FORCE_BUILD ON)
set(VTKDEMOS_SOURCE ${CMAKE_SOURCE_DIR})




